# .travis.yml - configuration file for the travis continuous integration service
# see http://about.travis-ci.org/docs/user/languages/php for more hints
#
language: php

# PHP versions to test against.
# See: http://docs.travis-ci.com/user/languages/php/
php:
  - 7.1

env:
  global:
    - DRUSH=tests/vendor/drush/drush/drush

before_install:
  - mkdir -v tests
install:
  - # $DRUSH qd --yes --no-server --root=docroot/ # @fixme
script:
  - ant -f base.xml build
